In [3]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [73., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name="weight1")
w2 = tf.Variable(tf.random_normal([1]), name="weight2")
w3 = tf.Variable(tf.random_normal([1]), name="weight3")
b = tf.Variable(tf.random_normal([1]), name="bias")
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis-Y))
# Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1 : x1_data, x2 : x2_data, x3 : x3_data,
                                             Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  112136.016 
Prediction:
 [-157.74394 -185.04108 -184.62321 -202.44571 -138.70944]
10 Cost:  1003.6708 
Prediction:
 [137.06676 169.46376 164.59041 177.85623 131.71515]
20 Cost:  1000.0236 
Prediction:
 [137.87177 170.59529 165.61946 178.99391 132.60478]
30 Cost:  997.408 
Prediction:
 [137.78748 170.65749 165.59512 178.98445 132.67873]
40 Cost:  994.80615 
Prediction:
 [137.7007  170.71626 165.56766 178.97151 132.74997]
50 Cost:  992.2173 
Prediction:
 [137.61414 170.7749  165.54024 178.95865 132.82101]
60 Cost:  989.6416 
Prediction:
 [137.52782 170.8334  165.51294 178.94586 132.89189]
70 Cost:  987.07996 
Prediction:
 [137.4417  170.8917  165.48564 178.93306 132.96251]
80 Cost:  984.5314 
Prediction:
 [137.35583 170.94989 165.45848 178.92035 133.03297]
90 Cost:  981.9964 
Prediction:
 [137.27017 171.00789 165.43132 178.90767 133.1032 ]
100 Cost:  979.4746 
Prediction:
 [137.18477 171.06577 165.40428 178.89505 133.17326]
110 Cost:  976.9655 
Prediction:
 [137.09955 171.12344 

1050 Cost:  790.7644 
Prediction:
 [130.00638 175.9207  163.12189 177.89641 138.99156]
1060 Cost:  789.2279 
Prediction:
 [129.93987 175.96562 163.10066 177.88783 139.04475]
1070 Cost:  787.6993 
Prediction:
 [129.8735  176.0104  163.07947 177.87927 139.09778]
1080 Cost:  786.1783 
Prediction:
 [129.80731 176.05507 163.05832 177.87076 139.15065]
1090 Cost:  784.6655 
Prediction:
 [129.74132 176.09962 163.03722 177.86229 139.20337]
1100 Cost:  783.15985 
Prediction:
 [129.67548 176.14407 163.01619 177.85385 139.25595]
1110 Cost:  781.662 
Prediction:
 [129.60982 176.18842 162.99521 177.84547 139.30838]
1120 Cost:  780.1721 
Prediction:
 [129.54434 176.23264 162.97429 177.83711 139.36067]
1130 Cost:  778.68896 
Prediction:
 [129.47899 176.27672 162.95341 177.82878 139.41278]
1140 Cost:  777.2145 
Prediction:
 [129.41385 176.32068 162.93257 177.82048 139.46474]
1150 Cost:  775.74664 
Prediction:
 [129.34886 176.36456 162.91182 177.81224 139.51657]
1160 Cost:  774.2863 
Prediction:
 [129.2

2000 Cost:  674.54285 
Prediction:
 [124.39588 179.70226 161.3218  177.23201 143.4136 ]
